package com.bluestone.app.core.event;


public enum EventType {
    
    ORDER_CREATED,
    ORDER_CANCELED,
    ON_PAYMENT_STARTED,
    CUSTOMER_LOGIN,
    CUSTOMER_REGISTERED,
    ORDER_STATUS_UPDATED, 
    ORDERITEM_STATUS_UPDATED, 
    ORDERITEM_SHIPPING_STATUS_UPDATED, 
    CART_CREATED,
    CART_UPDATED,
    ON_PAYMENT_RESPONSE, 
    ORDER_PAYMENT_STATUS_UPDATED, 
    GOLD_MINE_PLAN_PAYMENT, 
    GOLD_MINE_PLAN_ENROLMENT
}
